name: "Tag Docs Repo"
description: "Tags the docs repo and creates a release mentioning compatible versions of various SuperTokens SDKs"
on:
  push:
    branches:
      - maaster
runs:
  using: 'node16'
  main: '../dist/docs-versioning/index.js'

jobs:
  tag-docs:
    runs-on: ubuntu-latest
    name: Tag Docs Repo with SDK compatibility
    steps:
      - uses: actions/checkout@v3
      - name: Fetch last tag
        id: fetch_last_tag
        run: echo ::set-output name=tag::$(git describe --tags `git rev-list --tags --max-count=1`)
      - name: Tag Docs Repo
        uses: nkshah2/supertokens-actions/dist/docs-versioning
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          last-tag: ${{ steps.fetch_last_tag.outputs.tag }}