name: "Tag Docs Repo"
description: "Tags the docs repo and creates a release mentioning compatible versions of various SuperTokens SDKs"
inputs:
  GITHUB_TOKEN:
    description: "The GitHub token to use for authentication"
    required: true
runs:
  using: 'node16'
  main: '../../dist/docs-versioning/index.js'